[project]
name = "whisper_asr_colab"
version = "1.0.3"

dependencies =  [
    "faster-whisper@git+https://github.com/SYSTRAN/faster-whisper.git",
    "python-docx>=1",
    "yt-dlp",
    "ffmpeg-python>=0.2",
    "numpy>=1",
    "pandas>=2",
    "pyannote.audio>=3",
    "torch>=2.1.1 ",
]
