name: CI

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          python-version: "3.10"
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ffmpeg

      - name: Install module
        run: uv add --dev pytest ipython ipywidgets

      - name: Run pytest
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: uv run pytest tests
