name: CI

on:
  push:
    branches:
      - main
      - release

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install FFmpeg
        run: |
          sudo apt-get install -y ffmpeg

      - name: Install module
        run: |
          pip install -e .
          pip install pytest

      - name: Run pytest
        run: |
          pytest -v tests/test_asr.py
