name: CI

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install module
        run: |
          pip install .
          pip install pytest ipython ipywidgets ctranslate2==4.4.0

      - name: Run pytest
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest -v tests/test_asr.py
          pytest -v tests/test_diarize.py
          pytest -v tests/test_docx_generator.py
